### ISSUE TITLE
Cannot create Composer cache dir's

### ISSUE THREAD

**Issue by markshust** [mageinferno/docker-magento2-php#11]
Possible Composer cache retrieval error with fresh magento setup (host debian):

Logs when running initial setup:

```
Initializing setup...
Cannot create cache directory /var/www/.composer/cache/repo/https---repo.magento.com/, or directory is not writable. Proceeding without cache
Installing magento/project-community-edition (2.0.4)
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache
  - Installing magento/project-community-edition (2.0.4)
    Downloading: 100%         

Created project in .
Cannot create cache directory /var/www/.composer/cache/repo/https---repo.magento.com/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache
```

Setup still proceeds normally, it's possible this is not an issue.

**Comment by markshust** [comment]
Going to close this as it only applies during initial install, and doesn't seem to be causing any issues....

**Comment by danipolo** [comment]
same problem here...

**Comment by mwin007** [comment]
Fix?

**Comment by markshust** [comment]
Please see my last comment. It's a visual error, but doesn't seem to be causing any issues. If anyone has a fix though, I'd take it in.

**Comment by mwin007** [comment]
Great!  Thanks for the tip.  Have a good Labor Day weekend!  -Martin Nguyen

**Comment by caneraydinbey** [comment]
Any solution?

**Comment by markshust** [comment]
This is an open source project. Either learn how to read threads or learn how to contribute.

**Comment by chintanvadi** [comment]
Cannot create cache directory /home/chintan/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache?

**Comment by mwin007** [comment]
It's like a permission issue, so check your docker user permission.

**Comment by markshust** [comment]
There are zero errors with this message, so there is nothing wrong. If you want the warnings suppressed, please submit a PR, as previously mentioned.

**Comment by AkashicSeer** [comment]
can composer be any more of a pain in the ass with this BS? Where does it actually keep this directory? How do I find it on linux and how do I fix this BS
