### ISSUE TITLE
Install Xdebug

### ISSUE THREAD

**Issue by gabrielqs** [mageinferno/docker-magento2-php#13]
Hi Mark,

As this is a development environment, for most people it would be crucial to have xdebug installed on the php containers.

I have been able to get it running using something similar to this:

```
FROM mageinferno/magento2-php:7.0.5-fpm-0

RUN pecl install xdebug-beta && \
    docker-php-ext-enable xdebug

RUN touch /usr/local/etc/php/conf.d/xdebug.ini
RUN echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so" >> /usr/local/etc/php/conf.d/xdebug.ini
RUN echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/xdebug.ini
RUN echo "xdebug.remote_host=192.168.0.13" >> /usr/local/etc/php/conf.d/xdebug.ini
```

Big problem here is the ip. There is still no official Docker way to fetch the host's ip, at least none i could find. In any case it is still better to have something like this than having no xdebug or having to manually install xdebug every time you create the containers...

Do you see a better way to enable xdebug remote debugging than this one?

Cheers,
Gabriel

**Comment by markshust** [comment]
Good question and thanks for the snippet. I think we should think about this for a few. The images are focused on a development environment, however the same images should be agnostic for production (working on prod deploy process now).

It's most likely a good idea to create another container for this with the base of `magento2-php`, sort of like what you did. Since I don't believe there is any reason to run xdebug on prod, this is probably a good method. The IP address is a problem. Perhaps you can create a quick bash script which builds out the Dockerfile with the host ip? Because of this, it would probably be dependent on each host building out their own Dockerfile.

**Comment by gabrielqs** [comment]
Hey Mark, thanks for your response.

Good to hear you're working on the prod environment, that will be great. Are you planning on adding varnish to the stack?

Maybe it would be interesting to coordinate the xdebug configuration with your current development, in a way when the environment is not set to production we install xdebug and configure it.

How do you feel about using environment variables to define the host ip? I can create the bash script to "configure" the docker-compose file, setting the host's IP on the php containers environment variables. After that, instead of starting php-fpm as the command for the container, the docker-compose file could start another script which would do some configurations first, including the enabling and configuration of xdebug, and then start php-fpm. Makes sense?

Another way would be using something similar to this in the composer  ([original post](https://github.com/docker/docker/issues/1143#issuecomment-70052272)):

`docker run --add-host=dockerhost:$(ip route | awk '/docker0/ { print $NF }')`

Some work to be done on that ip command to make it platform agnostic, but could make things easier....

**Comment by dimasch** [comment]
Hey, Guys. My working configuration:

```
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.idekey=PHPSTORM
xdebug.remote_log="/tmp/xdebug.log"
xdebug.remote_host=192.168.1.34
```

Important after setup xdebug:
1. docker-compose restart
2. restart PHPSTORM

**Comment by markshust** [comment]
This has an odd implementation regarding local ip addresses that I can see bombing out on some installs. Also I'd like to keep these images platform-agnostic between dev/stage/prod, this throws things off a bit.

I'm wondering if we should create a separate process or image to build out xdebug just for dev/stage. I'm going to close this ticket for inactivity, but just need a more streamlined process here.
