### ISSUE TITLE
Magento is unable to be installed via composer

### ISSUE THREAD

**Issue by tikolakin** [mageinferno/docker-magento2-php#18]
Hi there, I'm facing the issue with mogento installation. 
/home/tiko/.composer/auth.json with credentials to magento and github is available and mounted in appdata container.

```
tiko@dell:~/dev/magento2-docker-compose$ docker-compose run --rm setup
Starting magento2dockercompose_appdata_1
Starting magento2dockercompose_dbdata_1
Initializing setup...


  [Composer\Downloader\TransportException]                                                                                                            
  The "https://repo.magento.com/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known  
  failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known                                                      

```

Thanks for any help,
ps: I was able to install magento with this docker-composer on last week (from the scratch). But can't anymore.

**Comment by tikolakin** [comment]
It seems to be nginx proxy issue
when I run composer self-update from php container it throws php_network_getaddresses

```
tiko@dell:~/dev/magento2-docker-compose$ docker exec -it magento2dockercompose_phpfpm_1 sh -c 'composer diagnose'
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: Warning: Accessing packagist.org over http which is an insecure protocol.
FAIL
[Composer\Downloader\TransportException] The "http://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known
failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known
```

btw: ping 8.8.8.8 works fine

```
tiko@dell:~/dev/magento2-docker-compose$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=49 time=50.5 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=49 time=50.3 ms
```

**Comment by markshust** [comment]
I've come across this error in the past, I'm not sure what causes it. I don't think it's anything specific to these Docker images, however we should find a fix for it.

It seems it is being blocked because it is using http. Is there any way to prefer or force use of https? I think this would be desired anyways, since everything is going https nowadays.

**Comment by markshust** [comment]
Possible non-evasive fix? http://codinginharmony.blogspot.com/2012/10/forcing-composer-to-use-https.html

**Comment by tikolakin** [comment]
Hi @markoshust , thank you for the idea, it will work
It was actually the issue with http, Composer uses http
Have a look please, I'm able to use composer now, the difference is only another internet connection, it's wired but everything is fine now:

```
tiko@dell:~/dev/magento2-docker-compose$ docker exec -it magento2dockercompose_phpfpm_1 sh -c 'composer diag'
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: Warning: Accessing packagist.org over http which is an insecure protocol.
OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: ****
Dev Public Key Fingerprint: ****
OK
Checking composer version: FAIL
You are not running the latest stable version, run `composer self-update` to update (1.1.2 => 1.1.3)
```

According to https://github.com/composer/composer/issues/1992#issuecomment-20869636 the issues is more about networks and can be solved by forcing http to https, using composer global settings I gues.
Thanks.

**Comment by markshust** [comment]
I'm reopening this, if this is the case, we should turn back on `composer self-update`. I removed it previously because a major bug in a composer update killed the entire process, but this isn't much better.

**Comment by tikolakin** [comment]
Yes, thank you, it's still the issue
I've just tested it with the another network - still getting issues with composer
But it seems issues is about curl

```
tiko@dell:~/dev/magento2-docker-compose$ docker-compose exec phpfpm curl -v https://github.com
* Rebuilt URL to: https://github.com/
* Hostname was NOT found in DNS cache
* Could not resolve host: github.com
* Closing connection 0
curl: (6) Could not resolve host: github.com
```

Might it be an issue with the proxy?

**Comment by markshust** [comment]
All fixed in `5.6-fpm-0` (note new naming scheme, just major:minor now)

**Comment by markshust** [comment]
Still building this out with some more fixes. Hang tight.

**Comment by markshust** [comment]
All built:
https://hub.docker.com/r/mageinferno/magento2-php/builds/
https://hub.docker.com/r/mageinferno/magento2-nginx/builds/

Note that these new dir's depend/mount to `/var/www/html` instead of `/srv/www`. The `www-data` user's home directory was `/var/www`, and the simplest change to get all the composer functionality working correctly was to change to this dir.

I just release 5.0.0 of the docker-compose file to https://github.com/mageinferno/magento2-docker-compose -- mainly a ton of fixes for composer. Automated builds with composer and all other composer functionality should now work with zero errors. This also brings back the ability to mount the composer cache from the host to the container, saving a ton of time with installs.
