### ISSUE TITLE
Gulp compiling compatibility

### ISSUE THREAD

**Issue by mattiaz88** [mageinferno/docker-magento2-php#22]
Due tough frontend development and better compiling with gulp nodejs extensions, what do you think about to install npm and gulp globally by default? 
In addition what do you think about to install all required nodejs extensions reading from the root file gulpfile.js if present (maybe directly in the setup of the project) ?

**Comment by markshust** [comment]
I wouldn't install node/npm/etc inside either the php or nginx containers, as that would break docker's single-responsibility (which I'm a supporter of). 

This would need to be in some sort of node/one-off container that executes gulp or build commands. I won't be building this, but I'd be open to contributions and here to answer & work out any questions!

I honestly think webpack is probably the way to go now.
