### ISSUE TITLE
Mail Sending

### ISSUE THREAD

**Issue by SchumacherFM** [mageinferno/docker-magento2-php#26]
Hi Mark,

thank you for this project. It gave us a great inspiration how to dockerize Magento2.

One questions remains: how to you handle sending emails? What are the best options?

Thanks for an answers ... even if this issue maybe incorrectly placed 8-)

Cyrill

**Comment by markshust** [comment]
No worries, typically only issues but questions like implementation details are just fine here :)

For emails, you should configure a third-party API such as mailgun. A local service should be a no-op in a docker environment, because you can't log or control the sending of emails if you have multiple similar docker containers running (same reason the cronjob should really be on it's own container or worker instance, -- can't guarantee the cron will only run once, so here we can't guarantee only one email will be sent).

**Comment by marvin-w** [comment]
Hi @markoshust,

thank you for your answer on this issue in the first place!

Your points are totally valid and understandable, but if one doesn't have multiple #similar# containers running #at the same time# and only use them for continuous integration and delete them afterwords I do believe that there is no issue in sending mails through a local service (that doesnt run a new daemon and therefore conflicts with the docker best practice of using only one process per container/image).

Same thing about the cron, in your image it's also in the same image as magento itself. Therefore I don't believe there should be any problem (if you have only one magento container running).

In which scenario do you have more than one magento container similar on one machine with the same codebase running simultaneusly (apart of scaling or clustering stuff)?

Generally speaking, for production environments using docker your answer is totally fine, but there should be a differentiation between DEV & production.

Thank you again for your fast reply!
pointerxr

**Comment by markshust** [comment]
If you are only running one container/instance, you are correct, there are no issues. However, to properly scale out horizontally and build this out (for example, let's say I wanted to run an instance across 10 machines with 3 docker containers a piece), a proper 12-factor app approach should be taken and migrate these off to their own run services or third-party/api tools.

In regards to dev vs production, the API approach would still work. You just setup dev accounts for mail sending, cron management, etc., and set env variables to determine which services the API's use. I always use mailgun in my nodejs projects, even in dev, just passing in dev environment variables to send to dev api accounts. It's a proper 1:1 testing with production envs.
