### ISSUE TITLE
ZIP package is not installed

### ISSUE THREAD

**Issue by dverkade** [mageinferno/docker-magento2-php#34]
ZIP package is not installed, but the ZIP extension is. This will probably result in some issues. Install the ZIP package as wel..

**Comment by markshust** [comment]
@dverkade can you make a PR for this and I'll merge it in

**Comment by dverkade** [comment]
Hi,

I have created pull request #35 for this issue.

**Comment by markshust** [comment]
Before we go ahead and start adding random packages........ is this just for prevention of issues, or did you have an issue with the zip package not being installed?

**Comment by dverkade** [comment]
Hi,

We are using this image to package a Magento 2 module to be put onto the Magento Marketplace. I noticed that the ZIP extension is being loaded, but the ZIP package is not. So it's not possible to create a zip package from the command line.

**Comment by dverkade** [comment]
Pull request is merged, closing this issue.
