### ISSUE TITLE
stuck at Updating dependencies (including require-dev)

### ISSUE THREAD

**Issue by Gujarats** [mageinferno/docker-magento2-php#38]
I tried to install using : mageinferno/magento2-php:7.0-fpm-1 image
but got stuck at this : 

```shell
Initializing setup...
Installing magento/project-community-edition (2.1.6)
 - Installing magento/project-community-edition (2.1.6) Loading from cache
Created project in .
Loading composer repositories with package information
Updating dependencies (including require-dev)

``` 

any idea how to solve this ?

**Comment by Gujarats** [comment]
and after a while waiting I go this new error : 
```shell
Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mo
de for more info
```
please help thanks

**Comment by Gujarats** [comment]
I manage it somehow by updating my composer to the lastes version
```shell
compsoer selfupdate
```
Now my compose version `Composer version 1.4.2 `

**Comment by lazerg** [comment]
> I manage it somehow by updating my composer to the lastes version
> 
> ```shell
> compsoer selfupdate
> ```
> 
> Now my compose version `Composer version 1.4.2 `

you wrote command wrong
