### ISSUE TITLE
Install Git for Composer `--prefer-source` option.

### ISSUE THREAD

**Issue by erfanimani** [mageinferno/docker-magento2-php#39]
I'm not sure whether this is intended as a dev/CI/CD or production container, but Git would be very useful (essential) in case Composer cannot download a release and has to check out a repository's source.

Git would be useful in dev/ci/cd environments, but not production. I don't think this intended for production regardless, because you don't need Composer on a prod server.. So this addition should be welcome - correct me if I'm wrong.

**Comment by markshust** [comment]
There are static binaries from Nexcess for install, in the case you don't want to use composer. Git is not required to install from these binaries and they should work quote well for install.

**Comment by erfanimani** [comment]
Thanks for your time and comment @markoshust. Unfortunately I'm not quite following your message. I'm using Composer to install Magento, including some third party modules. Sometimes I use `dev-master#hash` to reference the module version. Composer correctly fails with a message like "Failed to clone, Git was not found..."

What's your reasoning for not including Git in this container (see PR)?

**Comment by markshust** [comment]
Ah ok. Thank you for the explanation, that actually makes complete sense. I'm reopening this ticket and will be adding git in.

**Comment by markshust** [comment]
Merged this in https://github.com/mageinferno/docker-magento2-php/pull/40

Will include it in next release. I'll be reviewing this entire Docker image to ensure it works with the last few updates and major version of Magento.
