### ISSUE TITLE
theme-adminhtml-backend dependency error

### ISSUE THREAD

**Issue by mikados** [mageinferno/docker-magento2-php#7]
i get this error (clean installation):
- Installing magento/theme-adminhtml-backend (100.0.2)
  [ErrorException]
  copy(/src/vendor/magento/theme-adminhtml-backend/9846f5db99e277168a14632938f71431.zip): failed to open stream: No such file or directory

thanks

**Comment by markshust** [comment]
I need more info and/or info on how to replicate this. Also, I'm submitting new builds momentarily, please check to see if this is fixed in new builds
https://github.com/mageinferno/magento2-docker-compose
