### ISSUE TITLE
Can't upgrade magento version

### ISSUE THREAD

**Issue by gsc-dev** [mageinferno/docker-magento2-php#9]
This is due to the location of the download file in mage-setup

A publicly available source can be found here:
http://pubfiles.nexcess.net/magento/ce-packages/

**Comment by markshust** [comment]
@gsc-dev awesome! i was starting to load them into my google cloud storage, but if nexcess already offers this, all the better. good timing as i'm getting ready to upload new test builds right now.

**Comment by markshust** [comment]
Pushed out to rc0 tag. Please follow https://github.com/mageinferno/magento2-docker-compose/issues/5 for updates on the new tags/releases. The most recent one contains this fix.

**Comment by gsc-dev** [comment]
Works well @markoshust 

Can't wait to see the changes also applied to php 5.6 branch.

I use some extensions protected by zend guard. Would it be possible to add the loader to the image:

https://www.zend.com/en/products/loader/downloads

```
     wget .... zend-loader-php5.6-linux-x86_64.tar.gz 
     tar -zxvf zend-loader-php5.6-linux-x86_64.tar.gz
     cp zend-loader-php5.6-linux-x86_64/* /etc/php5/cli/
     echo "zend_extension = /etc/php5/cli/opcache.so" >> /etc/php5/cli/php.ini
     echo "zend_extension = /etc/php5/cli/ZendGuardLoader.so" >> /etc/php5/cli/php.ini
     echo "always_populate_raw_post_data = -1" >> /etc/php5/cli/php.ini     
```

**Comment by markshust** [comment]
@gsc-dev thanks for the info. once i confirm all is final & signed off for php 7 branch, i will definitely backport the changeset to php 5 branch.

thanks for the snippet above for zendguard. i don't see any reason not to add this in. do you have a related install script for ioncube?

**Comment by gsc-dev** [comment]
Great Mark,
Would be nice if changes are also appil

**Comment by gsc-dev** [comment]
@markoshust Thanks Mark,

I haven't used ioncube but I believe this is what you are looking for:

https://www.howtoforge.com/install-ioncube-loader-for-all-php-modes-cli-cgi-fcgi-and-fpm-on-debian-wheezy

Cheers

**Comment by markshust** [comment]
@gsc-dev thanks, I'll see what I can do about getting this in the next release. I didn't want to hold up the new builds to install + test the zendguard/ioncube out, as these last builds took some time to complete.

fyi i pushed out the new images (including php 5), info at https://github.com/mageinferno/magento2-docker-compose/issues/5#issuecomment-212506584
